Controllers/AuthorsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Models;
using Library.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Library.Areas.Identity.Data;

namespace Library.Controllers
{
    public class AuthorsController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<LibraryUser> userManager;

        private readonly ApplicationDbContext _context;

        public AuthorsController(ApplicationDbContext context, RoleManager<IdentityRole> roleManager,
            UserManager<LibraryUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        // GET: 
        public async Task<IActionResult> Index(string sortOrder,
                                                string currentFilter,
                                                string searchString,
                                                int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "fullname_desc" : "";
            ViewData["DepartmentSortParm"] = sortOrder == "Department" ? "department_desc" : "Department";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var author = from s in _context.Authors 
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                author = author.Where(s => s.FullName.Contains(searchString));
                                       
            }
            switch (sortOrder)
            {
                case "fullname_desc":
                    author = author.OrderByDescending(s => s.FullName);
                    break;
                case "Department":
                    author = author.OrderBy(s => s.Department);
                    break;
                case "department_desc":
                    author = author.OrderByDescending(s => s.Department);
                    break;
                default:
                    author = author.OrderBy(s => s.FullName);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Author>.CreateAsync(author.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Costumers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                   .Include(s => s.Books)
                    .AsNoTracking()
                .FirstOrDefaultAsync(m => m.AuthorId == id);
         
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }
        
        // GET: Costumers/Create
        public IActionResult Create()
        {
            return View();
        }
        
        // POST: Costumers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuthorId,FullName,Department, Grade, Email, Phone, OwnerID")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
        
        // GET: Costumers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }
        
        // POST: Costumers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AuthorId,FullName,Department, Grade, Email, Phone")] Author author)
        {
            if (id != author.AuthorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CostumerExists(author.AuthorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
        [Authorize]
        // GET: Costumers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.AuthorId == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }
        
        // POST: Costumers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var context = await _context.Authors.FindAsync(id);
            var author = _context.Authors.OrderBy(e => e.FullName).Include(e => e.Books).First();
            _context.Authors.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CostumerExists(int id)
        {
            return _context.Authors.Any(e => e.AuthorId == id);
        }
    }
}

Controllers/BooksController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Identity;
using Library.Areas.Identity.Data;
using Library.ViewModel;

namespace Library.Controllers
{
    public class BooksController : Controller

    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<LibraryUser> userManager;

        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;


        public BooksController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment,
            RoleManager<IdentityRole> roleManager,
            UserManager<LibraryUser> userManager)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string sortOrder,
                                                string currentFilter,
                                                string searchString,
                                                int? pageNumber)
        {


            ViewData["CurrentSort"] = sortOrder;

            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Title desc" : "";
            ViewData["ReleaseDateSortParm"] = sortOrder == "ReleaseDate" ? "ReleaseDate desc" : "ReleaseDate";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;

            }
            ViewData["CurrentFilter"] = searchString;



            var book = from s in _context.Books.Include(c => c.Authors)
                       select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                book = book.Where(s => s.Authors.FullName.Contains(searchString));

            }

            switch (sortOrder)
            {

                case "Title":
                    book = book.OrderByDescending(s => s.Title);
                    break;
                case "ReleaseDate desc":
                    book = book.OrderByDescending(s => s.ReleaseDate);
                    break;
                case "ReleaseDate":
                    book = book.OrderBy(s => s.ReleaseDate);
                    break;
                default:
                    book = book.OrderBy(s => s.Title);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Book>.CreateAsync(book.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                  .Include(c => c.Authors)
                    .Include(b =>b.Ratings)
                .FirstOrDefaultAsync(m => m.BookID == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName");

            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookID,AuthorID,Title,Snippet,,Ganre, ReleaseDate,File")] Book book)
        {
            if (ModelState.IsValid)
            {



                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(book.File.FileName);
                string extension = Path.GetExtension(book.File.FileName);
                book.FilePath = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/upload/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await book.File.CopyToAsync(fileStream);
                }

                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName", book.AuthorID);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName", book.AuthorID);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookID,AuthorID, Title,Ganre,Snippet,ReleaseDate,File")] Book book)
        {
            if (id != book.BookID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(book.File.FileName);
                    string extension = Path.GetExtension(book.File.FileName);
                    book.FilePath = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/upload/", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await book.File.CopyToAsync(fileStream);
                    }
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName", book.AuthorID);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(c => c.Authors)
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookID == id);
        }


        public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename is not availble");
            string wwwRootPath = _hostEnvironment.WebRootPath;
            string path = Path.Combine(wwwRootPath + "/upload/", filename);


            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        // Get content type
        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        // Get mime types
        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
    {
        {".txt", "text/plain"},
        {".pdf", "application/pdf"},
        {".doc", "application/vnd.ms-word"},
        {".docx", "application/vnd.ms-word"},
        {".xls", "application/vnd.ms-excel"},
        {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
        {".png", "image/png"},
        {".jpg", "image/jpeg"},
        {".jpeg", "image/jpeg"},
        {".gif", "image/gif"},
        {".csv", "text/csv"}
    };
        }

    }

}

Views/Shared/_IndexLayout.cshtml
@using Library.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<LibraryUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />
    <!-- font awesome -->
   <script src="https://kit.fontawesome.com/0ecaefd5d9.js" crossorigin="anonymous"></script>
   <script src='https://cdn.tiny.cloud/1/59ltx183bco137dr46h1yfjjohnslab1c3n7v3i3sxqimwar/tinymce/5/tinymce.min.js' referrerpolicy="origin">
  </script>
  <script>
    tinymce.init({
      selector: 'textarea'
    });
  </script>
  
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="" src="/images/logo-horizontal.jpg" />
                </a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
             data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
             aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>             
    <div class = "collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a style="font-size:1.5rem;" class="nav-link text-white me-3" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        
                        <li class="nav-item">
                            <a style="font-size:1.5rem;" class="nav-link text-white me-3" asp-area="" asp-controller="Books" asp-action="Index">Творби</a>
                        </li>
                        <li class="nav-item">
                            <a style="font-size:1.5rem;" class="nav-link text-white me-4" asp-area="" asp-controller="Authors" asp-action="Index">Автори</a>
                        </li>
                        <li class="nav-item">
                            <a  style="font-size:1.5rem;" class="nav-link text-white me-3" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        
       @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {

                            <li class="nav-item dropdown">
                                <button style="font-size:1.5rem;" type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown">
                                    Manage
                                </button>

                                <ul class="dropdown-menu" >
                                    <li> <a class="dropdown-item" asp-controller="Administration"
               asp-action="ListUsers">Users</a></li>
                                    <li> <a class="dropdown-item" asp-controller="Administration"
               asp-action="ListRoles">Roles</a></li>
                                    <li> <a class="dropdown-item" asp-controller="Admin"
               asp-action="Index">Uploaded Books</a></li>

                                </ul>
                            </li>
                        }

                    </ul>
                   
                </div>
            </div>
        </nav>
    </header>
    
        
            @RenderBody()
        
    

    <footer style="padding:20px"  class="border-top footer text-center text-white bg-dark  box-shadow">
        <div class="container">
            &copy; 2022 - The Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Library.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<LibraryUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />
    <!-- font awesome -->
   <script src="https://kit.fontawesome.com/0ecaefd5d9.js" crossorigin="anonymous"></script>
   <script src='https://cdn.tiny.cloud/1/59ltx183bco137dr46h1yfjjohnslab1c3n7v3i3sxqimwar/tinymce/5/tinymce.min.js' referrerpolicy="origin">
  </script>
  <script>
    tinymce.init({
      selector: 'textarea'
    });
  </script>
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="" src="/images/logo-horizontal.jpg" />
                </a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
             data-bs-target="#navbarSupportedContent"
             aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
    </button>             
    <div class=" collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a style="font-size:1.5rem;" class="nav-link text-white me-3" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                       
                        <li class="nav-item">
                            <a style="font-size:1.5rem;" class="nav-link text-white me-3" asp-area="" asp-controller="Books" asp-action="Index">Творби</a>
                        </li>
                        <li class="nav-item">
                            <a style="font-size:1.5rem;" class="nav-link text-white me-4" asp-area="" asp-controller="Authors" asp-action="Index">Автори</a>
                        </li>
                         <li class="nav-item">
                            <a  style="font-size:1.5rem;" class="nav-link text-white me-3" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
     @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {


             <li class="nav-item dropdown">
              <button style="font-size:1.5rem;" type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown">
            Manage
            </button>
        
        <ul class="dropdown-menu" >
           <li> <a class="dropdown-item" asp-controller="Administration"
               asp-action="ListUsers">Users</a></li>
             <li> <a class="dropdown-item" asp-controller="Administration"
               asp-action="ListRoles">Roles</a></li>
               <li> <a class="dropdown-item" asp-controller="Admin"
               asp-action="Index">Uploaded Books</a></li>
        
        </ul>
            </li>
    }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark  box-shadow ">
        <div class="container">
            &copy; 2022 - The Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>