Models/Book.cs
using Library.Areas.Identity.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models
{
    public class Book
    {
        
        public int BookID { get; set; }
        public int? AuthorID { get; set; }
        
        [StringLength(50, MinimumLength = 3)]
        [DisplayName("Заглавие")]
        public string? Title { get; set; }
        [DisplayName("Откъс")]
        public string? Snippet { get; set; }
        [DisplayName("Жанр")]
        public string? Ganre { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Дата на публикуване")]
        public DateTime? ReleaseDate { get; set; } = DateTime.Now;

        [DisplayName("Качи файл")]
        public string? FilePath { get; set; }
        [NotMapped]
        [DisplayName("Качи файл")]
        public IFormFile? File { get; set; }
        public int Rating { get; set; }
        [DisplayName("Статус")]
        public ContactStatus Status { get; set; }

        public Author? Authors { get; set; }
        public ICollection<Rating>? Ratings { get; set;}
        
        public enum ContactStatus
        {
            Submitted,
            Approved,
            Rejected
        }

        public decimal OverallRating { get
            {
               
               
                if (Ratings!=null&&Ratings.Count > 0)
                { return (Ratings.Average(x => x.Rank)); }

                return (0);
            } }
        
     
       
}
    }

Controllers/BooksController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Identity;
using Library.Areas.Identity.Data;
using Library.ViewModel;

namespace Library.Controllers
{
    public class BooksController : Controller

    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<LibraryUser> userManager;

        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;


        public BooksController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment,
            RoleManager<IdentityRole> roleManager,
            UserManager<LibraryUser> userManager)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string sortOrder,
                                                string currentFilter,
                                                string searchString,
                                                int? pageNumber)
        {


            ViewData["CurrentSort"] = sortOrder;

            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Title desc" : "";
            ViewData["ReleaseDateSortParm"] = sortOrder == "ReleaseDate" ? "ReleaseDate desc" : "ReleaseDate";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;

            }
            ViewData["CurrentFilter"] = searchString;



            var book = from s in _context.Books.Include(c => c.Authors)
                       select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                book = book.Where(s => s.Authors.FullName.Contains(searchString));

            }

            switch (sortOrder)
            {

                case "Title":
                    book = book.OrderByDescending(s => s.Title);
                    break;
                case "ReleaseDate desc":
                    book = book.OrderByDescending(s => s.ReleaseDate);
                    break;
                case "ReleaseDate":
                    book = book.OrderBy(s => s.ReleaseDate);
                    break;
                default:
                    book = book.OrderBy(s => s.Title);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Book>.CreateAsync(book.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                  .Include(c => c.Authors)
                    .Include(b =>b.Ratings)
                .FirstOrDefaultAsync(m => m.BookID == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName");

            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookID,AuthorID,Title,Snippet,,Ganre, ReleaseDate,File")] Book book)
        {
            if (ModelState.IsValid)
            {



                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(book.File.FileName);
                string extension = Path.GetExtension(book.File.FileName);
                book.FilePath = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/upload/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await book.File.CopyToAsync(fileStream);
                }

                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName", book.AuthorID);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName", book.AuthorID);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookID,AuthorID, Title,Ganre,Snippet,ReleaseDate,File")] Book book)
        {
            if (id != book.BookID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(book.File.FileName);
                    string extension = Path.GetExtension(book.File.FileName);
                    book.FilePath = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/upload/", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await book.File.CopyToAsync(fileStream);
                    }
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Authors, "AuthorId", "FullName", book.AuthorID);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(c => c.Authors)
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookID == id);
        }


        public async Task<IActionResult> Download(string filename)
        {
            if (filename == null)
                return Content("filename is not availble");
            string wwwRootPath = _hostEnvironment.WebRootPath;
            string path = Path.Combine(wwwRootPath + "/upload/", filename);


            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory, GetContentType(path), Path.GetFileName(path));
        }

        // Get content type
        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        // Get mime types
        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
    {
        {".txt", "text/plain"},
        {".pdf", "application/pdf"},
        {".doc", "application/vnd.ms-word"},
        {".docx", "application/vnd.ms-word"},
        {".xls", "application/vnd.ms-excel"},
        {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
        {".png", "image/png"},
        {".jpg", "image/jpeg"},
        {".jpeg", "image/jpeg"},
        {".gif", "image/gif"},
        {".csv", "text/csv"}
    };
        }

    }

}

Controllers/RatingController.cs
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Library.Areas.Identity.Data;
using Library.Data;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class RatingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private RoleManager<IdentityRole>? roleManager;
        private UserManager<LibraryUser>? userManager;

        public RatingController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment,
            RoleManager<IdentityRole> roleManager,
            UserManager<LibraryUser> userManager)
        {
            _context = context;
          
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SetRating(int bookId, decimal rank) 
        {
            Rating rating = new Rating();
            rating.Rank = rank;
            rating.BookID = bookId;
            rating.UserId = userManager.GetUserId(User);

           
            _context.Ratings.Add(rating);
            _context.SaveChanges();

          

           return RedirectToAction("Details", "Books", new { id = bookId });
        }

    }
}

Views/Books/Create.cshtml
@using static Library.Models.Book
@model Library.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h4>Сподели творба</h4>

<div class="row">
    <div class="col-md-10">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ratings" value="0">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorID" class="control-label"></label>
                <select asp-for="AuthorID" class ="form-control" asp-items="ViewBag.AuthorID" ></select>
            </div>
            <div class="form-group">
                <label asp-for="Ganre" class="control-label"></label>
               <select asp-for="Ganre" class="form-control" >
                   <option></option>
                   <option>Фантастика</option>
                   <option>Фентъзи</option>
                   <option>Исторически</option>
                   <option>Трилър</option>
                   <option>Поезия</option>
                   <option>Детска литература</option>
               </select>

                <span asp-validation-for="Ganre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Snippet" class="control-label">Кратък откъс:</label>
                <textarea asp-for="Snippet"  class="" ></textarea>
                <span asp-validation-for="Snippet" class="text-danger"></span>
            </div>
                          
            <div class="form-group">
                <label asp-for="File" class="control-label" ></label>
                <input asp-for="File" accept="upload/*"  />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>

            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Details.cshtml
@model Library.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>
 <hr />

<div class="jumbotron" style="background-image:url(/images/glasses.png);
background-repeat:no-repeat;background-position: right bottom; margin:auto">
  
   
    <dl class="row">
       
       <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Authors.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Authors.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ganre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ganre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Snippet)
        </dt>
        <dd class = "col-sm-10">
            <div class="snippet"> @Html.Raw(Model.Snippet)</div>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            <a asp-action="Download" asp-route-filename="@Model.FilePath">
            @Html.DisplayFor(model => model.FilePath)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
           @*  @{
                if (Model.Ratings.Count > 0)
                {
                    <p>The overall rating is @Model.Title is @Model.OverallRating</p>
                }
                else
                {
                    <p>Be the first to rate @Model.Title </p>

                }
            }
             @{for (int i = 1; i < 6; i++)
                    {
                       // @Html.ActionLink("<i class='fa@(Model.OverallRating<i?'-regular':'-solid') fa-star'></i>", "SetRating", "Rating", new {rank=@i,bookId=@Model?.BookID})
                        
                        <a asp-action="SetRating" asp-controller="Ratings" 
                        asp-route-rank="@i"  asp-route-bookid="@Model?.BookID" >
                            <i class="fa@(Model.OverallRating<i?"-regular":"-solid") fa-star"></i>
                         </a>
                            
                    }
            }
             *@

             
            @{
                if (Model.Ratings.Count > 0)
                {
                    <p>Общата оценка на "@Model.Title" е  @Model.OverallRating.ToString("0.00") от 5
                    @for (int i = 1; i < 6; i++)
                    {
                        // @Html.ActionLink("<i class='fa@(Model.OverallRating<i?'-regular':'-solid') fa-star'></i>", "SetRating", "Rating", new {rank=@i,bookId=@Model?.BookID})

                        <i class="fa@(Model.OverallRating<i?"-regular":"-solid") fa-star fa-2x"></i>
                    }
                    </p>
                }
                else
                {
                    <p>Бъди първия, който ще оцени  "@Model.Title" </p>

                }
            }
           
             <h3>Дайте вашата оценка</h3> 
             
           <form asp-action="SetRating" asp-controller="Rating"  asp-route-bookid="@Model?.BookID"
           >
                
                    @for (int i = 1; i < 6; i++)
                    {
                        <label class="container"> @i
                        <input type="radio" id="Rank" name="Rank" value="@i" /> 
                        <span class="checkmark"></span>
                       </label>
                    }
                    <input class="btn-link bg-danger text-white" type="submit" value="Гласувай" />
                    </form>

                                  
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BookID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Books/Edit.cshtml
@model Library.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1>Промени</h1>


<hr />
<div class="row">
      
    <div class="col-sm-8">
       <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookID" />
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorID" class="control-label"></label>
                <select asp-for="AuthorID" class ="form-control" asp-items="ViewBag.AuthorID" ></select>
            </div>
            <div class="form-group">
                <label asp-for="Ganre" class="control-label"></label>
                <input asp-for="Ganre" class="form-control" />
                <span asp-validation-for="Ganre" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
     
            <div class="form-group">
                <label asp-for="Snippet" class="control-label"></label>
                <input asp-for="Snippet" class="form-control" />
                <span asp-validation-for="Snippet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label" ></label>
                <input required asp-for="File" accept="image/*"  />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input  type="submit" value="Save" class="btn btn-primary" />
            </div>
             </form>
    </div>
   
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Books/Index.cshtml
@using Library.Areas.Identity.Data
@using Library.ViewModel
@using Microsoft.AspNetCore.Identity
@model PaginatedList<Library.Models.Book>
@inject SignInManager<LibraryUser> signInManager;
@inject UserManager<LibraryUser> UserManager;


@{
    ViewData["Title"] = "Index";
}

<h1>Произведения</h1>
@foreach (var item in Model) {
@if (item.Authors.OwnerID==UserManager.GetUserId(User) || User.IsInRole("Admin"))
                 
                        {
<p>
    <a asp-action="Create">Качи произведение</a>
</p>
                        }
}
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Търси по Автор: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            
            <a asp-action="Index">Върни се към пълния списък</a>
        </p>
    </div>
</form>
<table class="table table-hover">
    <thead class="table-dark">
        <tr>
            <th>
              <a id="intext" asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParm"]"
                asp-route-currentFilter="@ViewData["CurrentFilter"]" > Заглавие</a>
            </th>
            <th>
             Автор
            </th>
            
            <th>
                Жанр 
            </th>
            <th>
                <a id="intext" asp-action="Index" asp-route-sortOrder="@ViewData["ReleaseDateSortParm"]"
                asp-route-currentFilter="@ViewData["CurrentFilter"]" > Дата на публикуване </a>
            </th>
            <th>
                Файл
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Authors.FullName)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Ganre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                <a asp-action="Download" asp-route-filename="@item.FilePath">
                @Html.DisplayFor(modelItem => item.FilePath)
                </a>
            </td>
            
            <td>
                @if (item.Authors.OwnerID==UserManager.GetUserId(User) || User.IsInRole("Admin"))
                 
                        {
                <a asp-action="Edit" asp-route-id="@item.BookID" >Edit</a> 
                <a asp-action="Delete" asp-route-id="@item.BookID">Delete</a>
                        }
                <a asp-action="Details" asp-route-id="@item.BookID" >Details</a> |
                
            </td>
        </tr>
}
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Назад
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Напред
</a>